apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    orgId: 1
    id: 1
    uid: GaKO7Fx7k
    type: prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: GET
    user:
    password:
    database:
    basicAuth: false
    readOnly: false
    isDefault: true
