name: "Regression"
description: "Report an unexpected error while upgrading!"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### We use GitHub Issues to track bug reports, feature requests and regressions.

        **NOTE:** You don't need to answer questions, that you know aren't relevant.

        ---

  - type: checkboxes
    attributes:
      label: "Is there an existing issue that is already reporting this?"
      description: "Please search [here](../issues?q=is%3Aissue) to see if an issue already exists for the feature you are requesting."
      options:
        - label: "I have searched the existing issues."
          required: true

  - type: input
    attributes:
      label: "Potential Commit/PR that introduced the regression."
      description: "If you have time to investigate, what PR/date/version introduced this issue?"
      placeholder: "PR #123 or commit 5b3c4a4"

  - type: input
    validations:
      required: true
    attributes:
      label: "Project version"
      placeholder: "X.Y.Z -> Q.R.S"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the regression."
      description: "A clear and concise description of what the regression is."

  - type: textarea
    attributes:
      label: "Input code"
      description: "Write some code snippets, if you think it is worth it."

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description (or code) of what you expected to happened."

  - type: textarea
    attributes:
      label: "Other"
      description: |
        Anything else relevant? Logs, OS version, IDE, package manager, etc.
        **NOTE:** You can attach images, recordings or log files by clicking this area to highlight it and then dragging files in.
