version: "3"

services:
  redis:
    container_name: portals-redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server --save 10 1 --loglevel warning --requirepass rd-dev-pass
    ports:
      - 9994:6379
    networks:
      - portal-net
    volumes:
      - "redis-data:/data"

networks:
  portal-net:
    external: false
    driver: bridge

volumes:
  redis-data: {}
