version: "3"

services:
  redis:
    container_name: portals-redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server --save 60 5 --loglevel warning --requirepass b4as55_efq267g
    networks:
      - portals-net
    volumes:
      - "./_data/redis:/data"

  backend:
    container_name: portals-backend
    image: portal-backend:latest
    restart: unless-stopped
    networks:
      - portals-net
    environment:
      NODE_ENV: production
      THROTTLER_TTL: 30
      THROTTLER_REQ_PER_TTL: 90
      REDIS_HOST: portals-redis
      REDIS_PORT: 6379
      REDIS_PASS: b4as55_efq267g
    ports:
      - 9994:3000

networks:
  portals-net:
    external: false
    driver: bridge
