import {
  HomeConfig,
  Scrape24SataConfig,
  ScrapeDanasConfig,
  ScrapeDirektnoConfig,
  ScrapeDnevnikConfig,
  ScrapeDnevnoConfig,
  ScrapeIndexConfig,
  ScrapeJutarnjiConfig,
  ScrapeN1InfoConfig,
  ScrapeNacionalConfig,
  ScrapeNacionalnoConfig,
  ScrapeNetConfig,
  ScrapeNoviListConfig,
  ScrapeOtvorenoConfig,
  ScrapePoslovniConfig,
  ScrapeSlobodnaDalmacijaConfig,
  ScrapeSportskeNovostiConfig,
  ScrapeTelegramConfig,
  ScrapeTportalConfig,
  ScrapeVecernjiConfig,
  ScrapeZagrebConfig,
} from "@/configs";
import { Portals } from "@/common/enums";

export const PORTAL_SCRAPERS = {
  [Portals.HOME]: HomeConfig,
  [Portals.DANAS]: ScrapeDanasConfig,
  [Portals.DIREKTNO]: ScrapeDirektnoConfig,
  [Portals.DNEVNIK]: ScrapeDnevnikConfig,
  [Portals.DNEVNO]: ScrapeDnevnoConfig,
  [Portals.INDEX]: ScrapeIndexConfig,
  [Portals.JUTARNJI]: ScrapeJutarnjiConfig,
  [Portals.NET]: ScrapeNetConfig,
  [Portals.POSLOVNI]: ScrapePoslovniConfig,
  [Portals.SATA24]: Scrape24SataConfig,
  [Portals.SLOBODNA_DALMACIJA]: ScrapeSlobodnaDalmacijaConfig,
  [Portals.SPORTSKE_NOVOSTI]: ScrapeSportskeNovostiConfig,
  // [Portals.TELEGRAM]: ScrapeTelegramConfig,
  [Portals.TPORTAL]: ScrapeTportalConfig,
  [Portals.VECERNJI]: ScrapeVecernjiConfig,
  // [Portals.ZAGREB]: ScrapeZagrebConfig,
  [Portals.NOVI_LIST]: ScrapeNoviListConfig,
  [Portals.N1_INFO]: ScrapeN1InfoConfig,
  [Portals.NACIONAL]: ScrapeNacionalConfig,
  // [Portals.NACIONALNO]: ScrapeNacionalnoConfig,
  // [Portals.OTVORENO]: ScrapeOtvorenoConfig,
} as const;
