import {
  HomeConfig,
  Scrape24SataConfig,
  ScrapeDanasConfig,
  ScrapeDirektnoConfig,
  ScrapeDnevnikConfig,
  ScrapeDnevnoConfig,
  ScrapeIndexConfig,
  ScrapeJutarnjiConfig,
  ScrapeN1InfoConfig,
  ScrapeNacionalConfig,
  ScrapeNacionalnoConfig,
  ScrapeNetConfig,
  ScrapeNoviListConfig,
  ScrapeOtvorenoConfig,
  ScrapePoslovniConfig,
  ScrapeSlobodnaDalmacijaConfig,
  ScrapeSportskeNovostiConfig,
  ScrapeTelegramConfig,
  ScrapeTportalConfig,
  ScrapeVecernjiConfig,
  ScrapeZagrebConfig,
} from "@/configs";
import { Portals } from "@/common/enums";
import { disabled } from "./formatting";

export const PORTAL_SCRAPERS = {
  [Portals.HOME]: HomeConfig,
  [Portals.DANAS]: disabled(ScrapeDanasConfig),
  [Portals.DIREKTNO]: ScrapeDirektnoConfig,
  [Portals.DNEVNIK]: ScrapeDnevnikConfig,
  [Portals.DNEVNO]: ScrapeDnevnoConfig,
  [Portals.INDEX]: ScrapeIndexConfig,
  [Portals.JUTARNJI]: ScrapeJutarnjiConfig,
  [Portals.NET]: disabled(ScrapeNetConfig),
  [Portals.POSLOVNI]: ScrapePoslovniConfig,
  [Portals.SATA24]: Scrape24SataConfig,
  [Portals.SLOBODNA_DALMACIJA]: ScrapeSlobodnaDalmacijaConfig,
  [Portals.SPORTSKE_NOVOSTI]: ScrapeSportskeNovostiConfig,
  [Portals.TELEGRAM]: disabled(ScrapeTelegramConfig),
  [Portals.TPORTAL]: ScrapeTportalConfig,
  [Portals.VECERNJI]: ScrapeVecernjiConfig,
  [Portals.ZAGREB]: ScrapeZagrebConfig,
  [Portals.NOVI_LIST]: ScrapeNoviListConfig,
  [Portals.N1_INFO]: ScrapeN1InfoConfig,
  [Portals.NACIONAL]: disabled(ScrapeNacionalConfig),
  [Portals.NACIONALNO]: disabled(ScrapeNacionalnoConfig),
  [Portals.OTVORENO]: ScrapeOtvorenoConfig,
} as const;
