name: Continuous Integration

on:
  push:
    branches: [main, develop]
    paths_ignore:
      [
        "**.md",
        ".env",
        ".gitignore",
        ".prettierrc",
        ".prettierignore",
        ".github",
      ]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  ci:
    uses: Pinehood/ph-reusable-workflows/.github/workflows/node-ci.yml@main
    secrets: inherit
    with:
      build_cmd: "pnpm run build:swc"
      run_lint: true
      lint_cmd: "pnpm run lint"
      node_options: "--max_old_space_size=4096"
      ecr_repository: "ph-portals"
