name: CI/CD
on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]
jobs:
  integrate:
    name: Tests, Coverage & Lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          cache: "npm"
      - run: |
          npm ci
          npm run build --if-present
      - run: |
          npm run lint
          npm run test:cov
  build:
    needs: integrate
    name: Build Docker Image
    runs-on: self-hosted
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -f ./Dockerfile -t portals-backend:latest .
  deploy:
    needs: build
    name: Deploy Docker Image
    runs-on: self-hosted
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Trigger Deployment
        run: |
          echo TODO deployment stage
